name: CoopStat CI

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v2

      - name: Setup java environment
        uses: actions/setup-java@v1
        with: { java-version: 11 }

      - name: Assemble APK and Bundle
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease
          ./gradlew bundleRelease
